### ISSUE TITLE
Register this on NPM and add support for systemjs (commonjs or amd)

### ISSUE THREAD

**Issue by robertbaker** [adjohnson916/ng-click-select#4]
Need to add a package.json and modify the file to support loading it in systemjs, browserify, etc.

**Comment by adjohnson916** [comment]
@robertbaker, good idea - did you intend to work in this as PR? Otherwise I'll try to get to it.

**Comment by robertbaker** [comment]
It should be really easy and simple. If I can I'll do it today but I'm
really busy.

The script should live in your root

**Comment by adjohnson916** [comment]
@robertbaker, are you wanting this for the v2.x or [v1.x](https://github.com/adjohnson916/ng-click-select/tree/v1.x) version(s)?

**Comment by robertbaker** [comment]
1.x

**Comment by adjohnson916** [comment]
@robertbaker, I've added `package.json` as well as CommonJS support via UMD pattern, then tagged and published to NPM as v0.1.5. Please let me know if it doesn't work. Thanks!
